### ISSUE TITLE
Go to Top not Working

### ISSUE THREAD

**Issue by Winston1029** [Winston1029/FriendsHost#1]
In MainUI, the button that allow user to go to to of the listview is not working for Renren, Twitter, and Sina.
Only Facebook is working

**Comment by LIJI-Max** [comment]
hey,

this issue is fixed and commited. but don't how to log this issue. click
the link it show err page. will do a release tmr morning.

On Sat, Jul 7, 2012 at 10:41 PM, Winston <
reply@reply.github.com

**Comment by Winston1029** [comment]
Cool. I have commit a small change as well to change the initialize message when user first time login and no feed available in DB yet.

Pls remember to change FlurryUtil.bEnable = true when you publish. I think better to keep developers out of Flurry tracking.
